### ISSUE TITLE
Link redirect to suspicious site

### ISSUE THREAD

**Issue by PavlikSimon** [DanielArndt/netmate-flowcalc#3]
Hello,
link in the description seems to be no longer working.
http://netmate-meter.sourceforge.net/ redirects to http://www.ip-measurement.org/, which has suspicious content.
Can you please delete it? In case some wanderers came to check the repository...
Btw good work, thank you

**Comment by DanielArndt** [comment]
Interesting. Thanks for pointing this out, as I don't actively use this anymore.

I'll update the README as soon as I get a chance, it looks like this is the only link that still works related to this project:

https://sourceforge.net/projects/netmate-meter/

**Comment by DanielArndt** [comment]
Oops, totally forgot about this until now. Removed in https://github.com/DanielArndt/netmate-flowcalc/commit/ea12931a21c1cd2c1c6ba1d4bfed7d88fccad77d
